name: "Continuous Integration Checks on Omnivault."

on:
  push:
    branches:
      - main
      - continuous-integration
  pull_request:
    branches:
      - main
      - continuous-integration

# cancel any previous runs that are still in progress if a new one is queued.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env: # FIXME: https://github.com/orgs/community/discussions/26671
  WORKING_DIRECTORY: "."

jobs:
  setup-env:
    runs-on: ubuntu-latest
    outputs:
      working-directory: ${{ steps.set-env.outputs.working-directory }}
      ruff-script-location: ${{ steps.set-env.outputs.ruff-script-location }}
      ruff-output-filename: ${{ steps.set-env.outputs.ruff-output-filename }}
    steps:
      - name: Set environment variables
        id: set-env
        run: |
          echo "working-directory=." >> $GITHUB_ENV
          echo "ruff-script-location=scripts/devops/continuous-integration/lint_ruff.sh" >> $GITHUB_ENV
          echo "ruff-output-filename=ruff_resultsaaa.log" >> $GITHUB_ENV
  continuous-integration:
    needs: setup-env
    uses: ./.github/workflows/_continuous_integration.yaml
    with:
      working-directory: ${{ needs.setup-env.outputs.working-directory }}
      ruff-script-location: ${{ needs.setup-env.outputs.ruff-script-location }}
      ruff-output-filename: ${{ needs.setup-env.outputs.ruff-output-filename }}
    secrets: inherit