name: "Continuous Integration Checks on Omnivault."

on:
  push:
    branches:
      - main
      - continuous-integration
  pull_request:
    branches:
      - main
      - continuous-integration

# cancel any previous runs that are still in progress if a new one is queued.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env: # FIXME: https://github.com/orgs/community/discussions/26671
  WORKING_DIRECTORY: "."
  RUFF_SCRIPT_LOCATION: "scripts/devops/continuous-integration/lint_ruff.sh"
  RUFF_OUTPUT_FILENAME: "ruff_results.log"

jobs:
  continuous-integration:
    uses: ./.github/workflows/_continuous_integration.yaml
    with:
      working-directory: "."
      ruff-script-location: "scripts/devops/continuous-integration/lint_ruff.sh"
      ruff-output-filename: "ruff_results.log"
    secrets: inherit